name: Stack build

on: [push]

jobs:
  build:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: [8.10.2, 8.8.4, 8.6.5, 8.4.4, 8.2.2, 8.0.2]
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        # exclude:
        #   - os: macOS-latest
        #   - os: windows-latest
        include:
          - os: macOS-latest
            ghc: 8.10.2
          - os: windows-latest
            ghc: 8.10.1
    env:
      STACK_BUILD: "stack build --stack-yaml stack-${{ matrix.ghc }}.yaml --no-terminal --system-ghc --fast"

    steps:
      - uses: actions/checkout@v2.3.2

      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Cache dependencies
        uses: actions/cache@v2.1.0
        with:
          path: "~/.stack"
          # A unique cache is used for each stack.yaml.
          key: ${{ runner.os }}-new-${{ hashFiles(format('stack-{0}.yaml', matrix.ghc)) }}
          # runner.os is explained here:
          # https://stackoverflow.com/questions/57946173/github-actions-run-step-on-specific-os

      - name: Install dependencies.
        run: ${STACK_BUILD} --only-dependencies
          # --test

      - name: Build agda2lagda.
        run: ${STACK_BUILD}
          # --test

      - name: Run agda2lagda
        run: stack exec agda2lagda --help
