# https://markkarpov.com/post/github-actions-for-haskell-ci.html

name: Stack build

on: 
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]


jobs:
  build:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: [8.10.2, 8.8.4, 8.6.5, 8.4.4, 8.2.2, 8.0.2]
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        # exclude:
        #   - os: macOS-latest
        #   - os: windows-latest
        include:
          - os: macOS-latest
            ghc: 8.10.2
          - os: windows-latest
            ghc: 8.10.2
            # TODO: stack-yaml file for ghc: 8.10.1
    # env:
    #   STACK_BUILD: "stack build --stack-yaml stack-${{ matrix.ghc }}.yaml --no-terminal --system-ghc --fast"

    steps:
      - uses: actions/checkout@v2.3.2

      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1.3
        id:   my-setup  # <-- self-chosen identifier
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Pathes of the setup
        run: |
          echo "ghc-path    = ${{ steps.my-setup.outputs.ghc-path    }}"
          echo "cabal-path  = ${{ steps.my-setup.outputs.cabal-path  }}"
          echo "stack-path  = ${{ steps.my-setup.outputs.stack-path  }}"
          echo "cabal-store = ${{ steps.my-setup.outputs.cabal-store }}"
          echo "ghc-exe     = ${{ steps.my-setup.outputs.ghc-exe     }}"
          echo "cabal-exe   = ${{ steps.my-setup.outputs.cabal-exe   }}"
          echo "stack-exe   = ${{ steps.my-setup.outputs.stack-exe   }}"

      - name: Cache dependencies
        uses: actions/cache@v2.1.0
        with:
          path: "~/.stack"
          # A unique cache is used for each stack.yaml.
          key: ${{ runner.os }}-new-${{ hashFiles(format('stack-{0}.yaml', matrix.ghc)) }}
          # runner.os is explained here:
          # https://stackoverflow.com/questions/57946173/github-actions-run-step-on-specific-os

      - name: Build dependencies.
        run: stack build --stack-yaml stack-${{ matrix.ghc }}.yaml --no-terminal --color always --system-ghc --fast --only-dependencies
        # Windows does not like this:
        # run: ${STACK_BUILD} --only-dependencies
          # --test

      - name: Build and install agda2lagda.
        run: stack build --stack-yaml stack-${{ matrix.ghc }}.yaml --no-terminal --color always --system-ghc --fast --copy-bins
        # run: ${STACK_BUILD}
          # --test

      - name: Run agda2lagda.
        run: stack exec --system-ghc -- agda2lagda --help
